//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Compra
    {
        public int IdDetalleCompra { get; set; }
        public Nullable<int> Id_Boleto { get; set; }
        public Nullable<int> Id_Compra { get; set; }
    
        public virtual Boleto Boleto { get; set; }
        public virtual Compra Compra { get; set; }
    }
}
