//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Precio
    {
        public int Id_Precio { get; set; }
        public Nullable<decimal> Precio1 { get; set; }
        public Nullable<int> Id_Avion { get; set; }
        public Nullable<int> Id_Ruta { get; set; }
        public Nullable<int> Id_Seccion { get; set; }
    
        public virtual Avion Avion { get; set; }
        public virtual Clase Clase { get; set; }
        public virtual Ruta Ruta { get; set; }
    }
}
