//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ubicacion
    {
        public int Id_Ubicacion { get; set; }
        public string nombre_ubicacion { get; set; }
        public Nullable<int> id_avion { get; set; }
    
        public virtual Avion Avion { get; set; }
    }
}
